//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblctthuephong
    {
        public string mapt { get; set; }
        public string maphong { get; set; }
        public string ngay { get; set; }
        public string madv { get; set; }
        public string soluong { get; set; }
    }
}
