//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldichvu
    {
        public string madv { get; set; }
        public string tendv { get; set; }
        public string gia { get; set; }
        public string donvitinh { get; set; }
    }
}
