//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblhoadon
    {
        public string mahd { get; set; }
        public string ngaythanhtoan { get; set; }
        public string tongtien { get; set; }
        public string mapt { get; set; }
        public string makh { get; set; }
        public string username { get; set; }
    }
}
