//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblnhanvien
    {
        public string manv { get; set; }
        public string tennv { get; set; }
        public string gioitinh { get; set; }
        public string ngaysinh { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public string chucvu { get; set; }
    }
}
