//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblphieudatphong
    {
        public string mapd { get; set; }
        public string makh { get; set; }
        public string ngayden { get; set; }
        public string ngaydi { get; set; }
        public string sotiendat { get; set; }
        public string username { get; set; }
        public string tinhtrang { get; set; }
        public string songuoi { get; set; }
    }
}
